const menuItems = [
  { category: 'featured', name: 'Beef Steak', price: 'UGX 25,000', description: 'Juicy marinated steak with your choice of chips, wedges, mash or rice.', image: 'images/NewImages/food/beef-steak-compressed.jpg' },
  { category: 'featured', name: 'Chicken Pilau', price: 'UGX 20,000', description: 'Fragrant spiced rice with tender chicken, served with kachumbari.', image: 'images/NewImages/food/chicken-pilau-compressed.jpg' },
  { category: 'featured', name: 'Chicken Wrap', price: 'UGX 25,000', description: 'Stir-fried chicken toasted in sweet chilli with tomatoes, onions and pepper, wrapped in tortilla bread.', image: 'images/NewImages/food/chicken-wrap-compressed.jpg' },
  { category: 'featured', name: 'Beef Pizza', sizes: { small: 'UGX 35,000', large: 'UGX 45,000' }, description: 'Diced beef, carrots and green pepper in tomato sauce, finished with mixed herbs and cheese.', image: 'images/NewImages/food/beef-pizza-compressed.jpg' },
  { category: 'beef', name: 'Beef Steak', price: 'UGX 25,000', description: 'Juicy marinated steak, served with chips, wedges or mash.', image: 'images/NewImages/food/beef-steak-compressed.jpg' },
  { category: 'beef', name: 'Beef Curry', price: 'UGX 25,000', description: 'Beef cubes marinated and prepared with vegetables.', image: 'images/NewImages/food/beef-corner-category-compressed.jpg' },
  { category: 'beef', name: 'Beef Stew / Steak', price: 'UGX 25,000', description: 'Wet-fry beef steak, served with your choice of accompaniment.', image: 'images/NewImages/food/beef-corner-category-compressed.jpg' },
  { category: 'beef', name: 'Beef Stroganoff', price: 'UGX 25,000', description: 'Julienne-cut beef in a rich, creamy sauce.', image: 'images/NewImages/food/beef-stroganoff-compressed.jpg' },
  { category: 'beef', name: 'Pan Fried Beef', price: 'UGX 25,000', description: 'Marinated pan-fried beef with sautéed vegetables.', image: 'images/NewImages/food/beef-corner-category-compressed.jpg' },
  { category: 'pilau', name: 'Chicken Pilau', price: 'UGX 20,000', description: 'Fragrant rice cooked with tender chicken and spices, served with kachumbari.', image: 'images/NewImages/food/chicken-pilau-compressed.jpg' },
  { category: 'pilau', name: 'Chicken Wrap', price: 'UGX 25,000', description: 'Stir-fried chicken toasted in sweet chilli with tomatoes, onions and pepper, wrapped in tortilla bread.', image: 'images/NewImages/food/chicken-wrap-compressed.jpg' },
  { category: 'pilau', name: 'Beef Pilau', price: 'UGX 20,000', description: 'Fragrant rice cooked with tender beef and spices, served with kachumbari.', image: 'images/NewImages/food/pilau-category-compressed.jpg' },
  { category: 'pilau', name: 'Goat Pilau', price: 'UGX 20,000', description: 'Fragrant rice cooked with tender goat meat and spices, served with kachumbari.', image: 'images/NewImages/food/pilau-category-compressed.jpg' },
  { category: 'pilau', name: 'Egg Wrap', price: 'UGX 15,000', description: 'Spanish omelette with Thousand Island dressing, lettuce, tomatoes and onions in tortilla bread.', image: 'images/NewImages/food/spanish-omelette-compressed.jpg' },
  { category: 'pizza', name: 'Beef Pizza', sizes: { small: 'UGX 35,000', large: 'UGX 45,000' }, description: 'Diced beef, carrots and green pepper in tomato sauce, finished with mixed herbs and cheese.', image: 'images/NewImages/food/beef-pizza-compressed.jpg' },
  { category: 'pizza', name: 'Chicken Pizza', sizes: { small: 'UGX 35,000', large: 'UGX 45,000' }, description: 'Diced chicken, carrots and green pepper in tomato sauce, finished with mixed herbs and cheese.', image: 'images/NewImages/food/chicken-pizza-compressed.jpg' },
  { category: 'pizza', name: 'Margherita Pizza', sizes: { small: 'UGX 25,000', large: 'UGX 30,000' }, description: 'Sweet pomodoro sauce, olives, oregano and cheese.', image: 'images/NewImages/food/pizza-category-compressed.jpg' },
  { category: 'pizza', name: 'Hawaiian Pizza', sizes: { small: 'UGX 35,000', large: 'UGX 45,000' }, description: 'Ham, pineapple and cheese.', image: 'images/NewImages/food/pizza-category-compressed.jpg' },
  { category: 'pizza', name: 'Tuna Pizza', sizes: { small: 'UGX 35,000', large: 'UGX 45,000' }, description: 'Tuna, onions, green pepper and cheese.', image: 'images/NewImages/food/pizza-category-compressed.jpg' },
  { category: 'platters', name: 'Platter for 4 pax', price: 'UGX 90,000', description: 'Grilled chicken, wet-fry goat, nyama choma, rice, chapati and kachumbari.', image: 'images/NewImages/food/sharing-platter-for-four-compressed.jpg' },
  { category: 'platters', name: 'Platter for 8 pax', price: 'UGX 170,000', description: 'A generous spread of grilled chicken, wet-fry goat, nyama choma, rice, chapati and kachumbari.', image: 'images/NewImages/food/platters-category-compressed.jpg' }
];

const menuGrid = document.querySelector('#menu-grid');
const tabs = document.querySelectorAll('.menu-category-grid button');
const menuGroups = ['beef', 'pilau', 'pizza', 'platters'];
const categoryLabels = { beef: 'Beef corner', pilau: 'Pilau &amp; wraps', pizza: 'Pizza', platters: 'Platters' };
function priceMarkup(item, index) { if (item.sizes) return '<div class=\'menu-order-options\'><button type=\'button\' class=\'menu-add\' data-add-item data-item-index=\'' + index + '\' data-size=\'small\'><span>Small</span><strong>' + item.sizes.small + '</strong></button><button type=\'button\' class=\'menu-add\' data-add-item data-item-index=\'' + index + '\' data-size=\'large\'><span>Large</span><strong>' + item.sizes.large + '</strong></button></div>'; return '<div class=\'menu-order-options\'><button type=\'button\' class=\'menu-add menu-add-single\' data-add-item data-item-index=\'' + index + '\'><span>Add to order</span><strong>+ </strong></button></div>'; }
function cardMarkup(item) { const index = menuItems.indexOf(item); return '<article class=\'menu-card\'><div class=\'menu-card-image\'><img src=\'' + item.image + '\' alt=\'' + item.name + '\' loading=\'lazy\'></div><div class=\'menu-card-body\'><div class=\'menu-card-top\'><h3>' + item.name + '</h3>' + (item.sizes ? '<span class=\'menu-card-price menu-card-sizes\'><span><small>Small</small><strong>' + item.sizes.small + '</strong></span><span><small>Large</small><strong>' + item.sizes.large + '</strong></span></span>' : '<span class=\'menu-card-price\'>' + item.price + '</span>') + '</div><p>' + item.description + '</p>' + priceMarkup(item, index) + '</div></article>'; }
function centerCategoryTab(button) { const strip = document.querySelector('.menu-category-grid'); if (!strip || strip.scrollWidth <= strip.clientWidth) return; const target = button.offsetLeft - (strip.clientWidth - button.offsetWidth) / 2; strip.scrollTo({ left: Math.max(0, Math.min(target, strip.scrollWidth - strip.clientWidth)), behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); }
function setActive(category, centerTab = true) { tabs.forEach(button => { const active = button.dataset.category === category; const wasActive = button.classList.contains('active'); button.classList.toggle('active', active); button.setAttribute('aria-selected', String(active)); if (active && centerTab && !wasActive) centerCategoryTab(button); }); }
function observeMenuSections() { if (window.menuScrollHandler) { window.removeEventListener('scroll', window.menuScrollHandler); window.removeEventListener('resize', window.menuScrollHandler); } window.menuScrollHandler = () => { const sections = [...document.querySelectorAll('[data-menu-section]')]; if (!sections.length) return; const menuRect = menuGrid.getBoundingClientRect(); if (menuRect.top > window.innerHeight * 0.75 || menuRect.bottom < 150) { setActive('all', false); return; } const marker = Math.max(155, Math.min(245, window.innerHeight * 0.28)); const current = sections.filter(section => section.getBoundingClientRect().top <= marker).pop(); setActive(current ? current.dataset.menuSection : 'all'); }; window.addEventListener('scroll', window.menuScrollHandler, { passive: true }); window.addEventListener('resize', window.menuScrollHandler, { passive: true }); requestAnimationFrame(window.menuScrollHandler); }
function renderMenu(category = 'all') { if (category === 'all') { menuGrid.innerHTML = menuGroups.map(group => '<section class=\'menu-category-section\' data-menu-section=\'' + group + '\'><div class=\'menu-section-heading\'><span>' + categoryLabels[group] + '</span></div><div class=\'menu-section-grid\'>' + menuItems.filter(item => item.category === group).map(cardMarkup).join('') + '</div></section>').join(''); observeMenuSections(); } else { menuGrid.innerHTML = menuItems.filter(item => item.category === category).map(cardMarkup).join(''); if (window.menuObserver) window.menuObserver.disconnect(); } }
tabs.forEach(tab => tab.addEventListener('click', () => { const category = tab.dataset.category; setActive(category); if (category === 'all') { renderMenu('all'); document.querySelector('[data-menu-section]').scrollIntoView({ behavior: 'smooth', block: 'start' }); } else { renderMenu('all'); const section = document.querySelector('[data-menu-section=' + category + ']'); if (section) section.scrollIntoView({ behavior: 'smooth', block: 'start' }); } }));
renderMenu('all');

document.addEventListener('click', event => { const button = event.target.closest('.quick-fab-toggle'); if (!button) return; const fab = button.closest('.quick-fab'); const open = fab.classList.toggle('is-open'); button.setAttribute('aria-expanded', String(open)); button.setAttribute('aria-label', open ? 'Close quick actions' : 'Open quick actions'); }); document.addEventListener('click', event => { const link = event.target.closest('.quick-fab-actions a'); if (!link) return; const fab = link.closest('.quick-fab'); const button = fab.querySelector('.quick-fab-toggle'); fab.classList.remove('is-open'); button.setAttribute('aria-expanded', 'false'); button.setAttribute('aria-label', 'Open quick actions'); });

document.addEventListener('click', event => { const speedDial = document.querySelector('.speed-dial'); if (speedDial && !event.target.closest('.speed-dial')) { speedDial.classList.remove('is-open'); const toggle = speedDial.querySelector('.speed-dial-toggle'); const actions = speedDial.querySelector('.speed-dial-actions'); toggle.setAttribute('aria-expanded', 'false'); actions.setAttribute('aria-hidden', 'true'); } }); document.addEventListener('keydown', event => { if (event.key !== 'Escape') return; const speedDial = document.querySelector('.speed-dial'); if (!speedDial) return; speedDial.classList.remove('is-open'); speedDial.querySelector('.speed-dial-toggle').setAttribute('aria-expanded', 'false'); speedDial.querySelector('.speed-dial-actions').setAttribute('aria-hidden', 'true'); });

const header = document.querySelector('.site-header');
const toggle = document.querySelector('.menu-toggle');
const root = document.documentElement;
function syncHeaderHeight() { root.style.setProperty('--site-header-height', header.getBoundingClientRect().height + 'px'); }
function updateHeader() { header.classList.toggle('scrolled', window.scrollY > 30); requestAnimationFrame(syncHeaderHeight); }
syncHeaderHeight();
window.addEventListener('scroll', updateHeader, { passive: true });
window.addEventListener('resize', syncHeaderHeight, { passive: true });
toggle.addEventListener('click', () => { const open = header.classList.toggle('menu-open'); toggle.setAttribute('aria-expanded', String(open)); requestAnimationFrame(syncHeaderHeight); });
document.querySelectorAll('.mobile-nav a').forEach(link => link.addEventListener('click', () => { header.classList.remove('menu-open'); toggle.setAttribute('aria-expanded', 'false'); }));
